services:
  mysql:
    image: mysql:8.0
    container_name: sl-mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - sl-mysql
networks:
  sl-mysql:
    driver: bridge
volumes:
  mysql-data:
    driver: local