CREATE USER IF NOT EXISTS 'jy'@'%' IDENTIFIED BY '123123';
CREATE USER IF NOT EXISTS 'jy'@'localhost' IDENTIFIED BY '123123';
GRANT ALL PRIVILEGES ON *.* TO 'jy'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'jy'@'localhost';
FLUSH PRIVILEGES;